### ISSUE TITLE
Ampersand cause LayoutException

### ISSUE THREAD

**Issue by way2muchnoise** [AfterLifeLochie/fontbox#13]
It can be reproduced with the demo book. When changing the body font to Ampersand it gives following stack trace

```
net.afterlifelochie.fontbox.layout.LayoutException: Produced invalid line configuration: 395 > 368!
    at net.afterlifelochie.fontbox.document.Element.boxText(Element.java:408)
    at net.afterlifelochie.fontbox.document.Element.boxText(Element.java:169)
    at net.afterlifelochie.fontbox.document.Paragraph.layout(Paragraph.java:46)
    at net.afterlifelochie.fontbox.layout.DocumentProcessor.pushElement(DocumentProcessor.java:113)
    at net.afterlifelochie.fontbox.layout.DocumentProcessor.generatePages(DocumentProcessor.java:91)
    at net.afterlifelochie.demo.GuiDemoBook.<init>(GuiDemoBook.java:87)
    at net.afterlifelochie.demo.ItemDemoBook.onItemRightClick(ItemDemoBook.java:23)
```

![](http://puu.sh/gvWb7/9b8aa53538.png)
Font change is marked in blue. I don't know what is going wrong here but seems that something goes wrong in the line width calculation. I don't know if it is intended to throw this or if it as there to prevent other weirdness

**Comment by AfterLifeLochie** [comment]
Yeah, this is meant to be thrown: `395 > 368` means the line is `395` units long and the maximum in the parent container (the page) was only `368`.

Assuming the font object is not null, I'll have to look into this.

**Comment by AfterLifeLochie** [comment]
This should theoretically be resolved by the implementation of `LineWriter` to handle writing of whole lines on the page. Can you let me know if this is not the case?
